### PR TITLE
feat: add signal support and fix timeout, closes #5

### LINKED ISSUE #5: Add support for aborting (preferably via AbortSignal)

### LINKED ISSUE #71: Add Node 22 to CI
https://nodejs.org/en/blog/announcements/v22-release-announce

### PR DESCRIPTION
**Pull request by sublimator**
1. Added a new function `combineSignals` in `src/client.js` to merge AbortSignal instances.
1. Updated the `_request` method in `src/client.js` to accept an additional argument `signal` and use the `combineSignals` function to merge with a default timeout signal. 
1. Refactored the `chat` and `chatStream` methods in `src/client.js` to use a single object `data` for the main chat configuration and an additional options object `options`, where the signal is passed.
1. Updated the build and publish workflow to include Node.js version 22 in the matrix (closes #71 )

### CODE REVIEW

File: src/client.js [hunk 1]
```diff
@@ -82,7 +83,7 @@ class MistralClient {
         'Authorization': `Bearer ${this.apiKey}`,
       },
       body: method !== 'get' ? JSON.stringify(request) : null,
-      timeout: this.timeout * 1000,
+      signal: signal ?? AbortSignal.timeout(this.timeout * 1000),
```
Comment (sublimator) [inline src/client.js:86]: Due to the limitations of what's possible when attempting to merge a user provided signal and a timeout signal, this simple approach may be the best that can be done without passing in an AbortController and implementing a timeout that calls its abort method. Thus if the user provides a signal, they are responsible for managing timeouts as well. This would be non-obvious to most users though. On the flip side, passing around an AbortController seems non-standard. 

We could document the parameter with something along these lines:
"Users must manage timeouts for their own AbortSignals. Without a user-provided signal, a default timeout of [x] seconds applies automatically."

Comment (sublimator) [reply src/client.js:86]: Actually, that may not be the case re: merging, as the signal.reason /is/ available and should be possible to transfer to a new merged signal.

**Comment by sublimator** [comment]
@lerela @fuegio

When you get a chance? 

Thx

**Review by fuegoio — APPROVED** [review]
LGTM 👍

**Comment by sublimator** [comment]
@lerela 

Let's go!

File: src/client.js [hunk 2]
```diff
@@ -221,6 +246,8 @@ class MistralClient {
    * @param {*} safePrompt whether to use safe mode, e.g. true
    * @param {*} toolChoice the tool to use, e.g. 'auto'
    * @param {*} responseFormat the format of the response, e.g. 'json_format'
+   * @param {*} [signal] - optional AbortSignal instance to control request
```
Comment (sublimator) [inline src/client.js:249]: Actually, it might be worth considering whether to move `signal` into a second object param, and keep it out of the bag of data that is sent to the server. It's a bit cleaner that way. 

On a related note, I realised that the JSDoc comments are actually incorrect ([see](https://github.com/mistralai/client-js/issues/70#issuecomment-2095044637))
