### PR TITLE
fix: typescript definitions

### LINKED ISSUE #62: mistralClient types dont contain `maxRetries` nor `timeout`
Is there a specific reason for not exposing `maxRetries` from MistralClient ? 

also I do see `timeout` parameter is passed to fetch options but dont think thats a valid parameter as per docs 
https://developer.mozilla.org/en-US/docs/Web/API/fetch. Might be moving to typescript can fix such issues. 

If these are just misses, happy to submit a PR to fix this issue.

### LINKED ISSUE #67: Error: An interface property cannot have an initializer
The typescript definitions have an error (TS1246) as seen in the screenshot:

image

This happens because an interface cannot be instantiated, thus it does not make sense to have an initializer.

At least, [ToolCalls](https://github.com/mistralai/client-js/blob/06dabd32e702e31dd43950acec5cc181e47f8301/src/client.d.ts#L49) and [ResponseFormat](https://github.com/mistralai/client-js/blob/06dabd32e702e31dd43950acec5cc181e47f8301/src/client.d.ts#L65) suffer from this problem.

### LINKED ISSUE #69: HTTP 400: Tool call id was null but must be a-z, A-Z, 0-9, with a length of 9
I am getting this error when using one of the open source models, but not with the largest one. The stacktrace that I am getting is the following:

```
MistralAPIError: HTTP error! status: 400 Response: 
{"object":"error","message":"Tool call id was null but must be a-z, A-Z, 0-9, with a length of 9.","type":"invalid_request_error","param":null,"code":null}
    at MistralClient._request (file://...@mistralai/mistralai/src/client.js:132:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MistralClient.chatStream (file:///...@mistralai/mistralai/src/client.js:306:22)
``` 

It seems that the typescript definitions of the client are forcing the tool calls to have an ID equal to the string "null". This seems to be working fine with some models (`mistral-large-latest`) but is raising errors with other models (`open-mixtral-8x22b`).

The definition that is currently in the typescript client is this:

```typescript
export interface ToolCalls {
    id: 'null';
    type: ToolType = ToolType.function;
    function: FunctionCall;
}
```

I am using Mistral's client within LangChain.

### PR DESCRIPTION
**Pull request by sublimator**
This should make the typescript definitions at least useable. Currently they seem to be quite broken (per #69, #67 )  

Closes #54 
Closes #47 
Closes #69 
Closes #67 
Closes #62 

- Adds examples/typescript and build in CI step
- Fixes definitions (trying to set defaults, chatStream returning wrong type)
- Add signal (per #68) to typescript definitions 
- Fix interfaces (non-exhaustively) per: https://docs.mistral.ai/redocusaurus/plugin-redoc-0.yaml

### CODE REVIEW

**Comment by sublimator** [comment]
@fuegoio

Please look :)

File: src/client.d.ts [hunk 1]
```diff
@@ -1,194 +1,177 @@
...
+  object: 'list';
+  data: Embedding[];
+  model: string;
+  usage: TokenUsage;
+}
+
+export interface Message {
+  role: string;
+  // TODO: this is not specified at https://docs.mistral.ai/redocusaurus/plugin-redoc-0.yaml
+  name?: string,
```
Comment (fuegoio) [inline src/client.d.ts:127]: Normally there is no `name` on the message, I think we can remove it.

File: src/client.d.ts [hunk 2]
```diff
@@ -1,194 +1,177 @@
...
+  name: string;
+  arguments: string;
+}
+
+export interface ToolCalls {
+  id: string;
+  function: FunctionCall;
+}
+
+export enum ResponseFormats {
```
Comment (fuegoio) [inline src/client.d.ts:52]: I think we should also remove the enums from the types and change them to types. A simple example like this does not work because the enums are TS only:

```ts
import MistralClient, { ResponseFormats } from "@mistralai/mistralai";

const chatResponse = await mistralClient.chat({
    model: "mistral-large",
    temperature: 0.1,
    responseFormat: { type: ResponseFormats.json_object },
})`
```

This raises the error `'mistralai/src/client.js' does not provide an export named 'ResponseFormats'`

**Comment by sublimator** [comment]
>
> I suppose someone put "name" in there for OpenAI compat reasons at some
point, though it is just misleading, and also not necessary

**Comment by sublimator** [comment]
Oh right, yeah, the enums aren't even defined at runtime are they. I added
literals (for ergonomics) and left the enums in there and moved on. They
are completely broken though aren't they.

A good argument to move to TS :)

**Comment by fuegoio** [comment]
> Oh right, yeah, the enums aren't even defined at runtime are they. I added literals (for ergonomics) and left the enums in there and moved on. They are completely broken though aren't they. A good argument to move to TS :)

In a `d.ts` file they do not make much sense no. I approve moving to TS to have this kind of nice feature.

**Comment by sublimator** [comment]
@fuegoio 

Anything else? I'll look at a full TS port when I have more time

**Comment by sublimator** [comment]
Oh, wait, that's not working, enums still referenced, but no errors, hrmmm

File: src/client.d.ts [hunk 3]
```diff
@@ -1,194 +1,160 @@
...
-
-    export interface FunctionCall {
-        name: string;
-        arguments: string;
-    }
-
-    export interface ToolCalls {
-        id: 'null';
-        type: ToolType = ToolType.function;
-        function: FunctionCall;
```
Comment (sublimator) [inline src/client.d.ts:50]: What happened here? :)

Comment (fuegoio) [reply src/client.d.ts:50]: What do you mean?

Comment (sublimator) [reply src/client.d.ts:50]:
```
id: 'null';
type: ToolType = ToolType.function;
```

As you mentioned, the enums don't work at runtime, and `null` is set to match the string null, not the null *type* (which is actually not appropriate either). Also, it's trying to set a default (`ToolType = ToolType.function;`) inside a `.d.ts` file, which I don't believe actually works. 

More a rhetorical question than serious :) Wondering how the ..

**Comment by sublimator** [comment]
>  I'll look at a full TS port when I have more time

In a separate PR, to be clear

File: src/client.d.ts (hunk 3 above)
Comment (fuegoio) [reply src/client.d.ts:50]: Yeah the `null` string is expected, as before our API change the id returned by the API was always `'null'` (the string). Now it is function call ids yes. The default stuff well I'm not sure ahah

**Review by fuegoio — APPROVED** [review]
Thanks a lot @sublimator!
